import type { LecturerModel } from '../manageModel'

const lecturerList: LecturerModel[] = [
  {
    id: '422a6948-9868-4a69-e375-08dbc25fd71b',
    email: null,
    normalizedEmail: null,
    emailConfirmed: false,
    phoneNumber: '00009992211',
    phoneNumberConfirmed: false,
    twoFactorEnabled: false,
    lockoutEnd: null,
    lockoutEnabled: false,
    filePath: null,
    displayName: 'teredew',
    department: null,
    departmentHead: null,
    createdBy: 'Undefined',
    createdAt: '0001-01-01T00:00:00',
  },
  {
    id: 'eee5ffb8-d493-4407-abd0-08dbc589979b',
    email: null,
    normalizedEmail: null,
    emailConfirmed: false,
    phoneNumber: null,
    phoneNumberConfirmed: false,
    twoFactorEnabled: false,
    lockoutEnd: null,
    lockoutEnabled: true,
    filePath: null,
    displayName: null,
    department: null,
    departmentHead: null,
    createdBy: 'Undefined',
    createdAt: '0001-01-01T00:00:00',
  },
  {
    id: '2509c552-2442-4988-6687-08dbc5b99d3a',
    email: null,
    normalizedEmail: null,
    emailConfirmed: false,
    phoneNumber: null,
    phoneNumberConfirmed: false,
    twoFactorEnabled: false,
    lockoutEnd: null,
    lockoutEnabled: true,
    filePath:
      'https://res.cloudinary.com/dd9f1tyca/image/upload/v1697945242/gkio53xo0bywpx3rfsyj.png',
    displayName: 'aloootest',
    department: null,
    departmentHead: null,
    createdBy: 'Undefined',
    createdAt: '0001-01-01T00:00:00',
  },
  {
    id: '54b5059e-bb93-4430-c66b-08dbc5bd29bc',
    email: null,
    normalizedEmail: null,
    emailConfirmed: false,
    phoneNumber: null,
    phoneNumberConfirmed: false,
    twoFactorEnabled: false,
    lockoutEnd: null,
    lockoutEnabled: true,
    filePath: null,
    displayName: null,
    department: null,
    departmentHead: null,
    createdBy: 'Undefined',
    createdAt: '0001-01-01T00:00:00',
  },
  {
    id: '36cb6cc3-86c3-4e71-ad01-08dbd16d67db',
    email: null,
    normalizedEmail: null,
    emailConfirmed: false,
    phoneNumber: null,
    phoneNumberConfirmed: false,
    twoFactorEnabled: false,
    lockoutEnd: null,
    lockoutEnabled: true,
    filePath: null,
    displayName: 'Undefined',
    department: null,
    departmentHead: null,
    createdBy: '358678c8-a1f7-42e4-b83e-08dbc25fd46c',
    createdAt: '2023-10-20T20:06:42.3989044',
  },
]

export default lecturerList
