import type { LecturerModel } from '../manageModel'

const lecturerList: LecturerModel[] = [
  {
    name: 'RaeKyuoo',
    email: 'raekyo@gmail.com',
    phone: '090878688',
    department: 'Computer Science',
    subject: 'Basic Operating System',
    status: 'offline',
  },
  {
    name: 'JohnDoe',
    email: 'johndoe@example.com',
    phone: '555-123-4567',
    department: 'Computer Science',
    subject: 'Basic Operating System',
    status: 'online',
  },
  {
    name: 'JaneSmith',
    email: 'janesmith@example.com',
    phone: '555-987-6543',
    department: 'Computer Science',
    subject: 'Basic Operating System',
    status: 'offline',
  },
  {
    name: 'DavidWilson',
    email: 'davidwilson@example.com',
    phone: '555-555-5555',
    department: 'Computer Science',
    subject: 'Basic Operating System',
    status: 'online',
  },
  {
    name: 'SarahBrown',
    email: 'sarahbrown@example.com',
    phone: '555-321-9876',
    department: 'Computer Science',
    subject: 'Basic Operating System',
    status: 'offline',
  },
  {
    name: 'MichaelJones',
    email: 'michaeljones@example.com',
    phone: '555-888-1234',
    department: 'Computer Science',
    subject: 'Basic Operating System',
    status: 'online',
  },
  {
    name: 'LauraDavis',
    email: 'lauradavis@example.com',
    phone: '555-444-7777',
    department: 'Computer Science',
    subject: 'Basic Operating System',
    status: 'offline',
  },
  {
    name: 'AlexParker',
    email: 'alexparker@example.com',
    phone: '555-333-9999',
    department: 'Computer Science',
    subject: 'Basic Operating System',
    status: 'online',
  },
  {
    name: 'GraceJohnson',
    email: 'gracejohnson@example.com',
    phone: '555-666-2222',
    department: 'Computer Science',
    subject: 'Basic Operating System',
    status: 'offline',
  },
  {
    name: 'DanielLee',
    email: 'daniellee@example.com',
    phone: '555-111-3333',
    department: 'Computer Science',
    subject: 'Basic Operating System',
    status: 'online',
  },
  {
    name: 'SophiaTurner',
    email: 'sophiaturner@example.com',
    phone: '555-777-8888',
    department: 'Computer Science',
    subject: 'Basic Operating System',
    status: 'offline',
  },
  {
    name: 'RobertHill',
    email: 'roberthill@example.com',
    phone: '555-222-1111',
    department: 'Computer Science',
    subject: 'Basic Operating System',
    status: 'online',
  },
  {
    name: 'EmilyClark',
    email: 'emilyclark@example.com',
    phone: '555-999-4444',
    department: 'Computer Science',
    subject: 'Basic Operating System',
    status: 'offline',
  },
  {
    name: 'WilliamWhite',
    email: 'williamwhite@example.com',
    phone: '555-333-5555',
    department: 'Computer Science',
    subject: 'Basic Operating System',
    status: 'online',
  },
  {
    name: 'OliviaSmith',
    email: 'oliviasmith@example.com',
    phone: '555-888-1111',
    department: 'Computer Science',
    subject: 'Basic Operating System',
    status: 'offline',
  },
]

export default lecturerList
